### ISSUE TITLE
Create a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by unnikrishnan2002** [unnikrishnan2002/Note-It#1]
Create a CONTRIBUTING.md file that basically answers the following questions.
- [ ] How to set up this project on their local system
- [ ] How to add add their changes , commit and push to the forked branch
- [ ] How to raise a Pull request
- [ ] And , how to create issues for requesting a new feature or suggesting a better change in any file

Refer to [Contributing guidelines](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) and also add something which you feel like will help beginner contributors

**Comment by parth-gpt** [comment]
Can I work on this?
As a beginner myself I can add the data in a better way following the pointers given by you.

**Comment by unnikrishnan2002** [comment]
> Can I work on this? As a beginner myself I can add the data in a better way following the pointers given by you.

Yeah sure. Please go ahead, give the information in such a way that it makes it easy to figure out everything, and use `code blocks` for git commands .

**Comment by parth-gpt** [comment]
Yeah will try my best!

**Comment by unnikrishnan2002** [comment]
fixes #3
