### ISSUE TITLE
Images are not visible in readme and Readme can be improved 

### ISSUE THREAD

**Issue by Navaneeth-Sharma** [unnikrishnan2002/Note-It#4]
The Image urls are not properly set in readme. 
Readme.md and docs can be improved  for absolute beginners in android dev

**Comment by unnikrishnan2002** [comment]
Hey @Navaneeth-Sharma the images are not set because a slight UI change is needed in the app so it will be set after the UI changes are made . And regarding the Readme file if you have any suggestion you can drop your views here and we can discuss about those changes 

Thank you
